# Auth configuration using golang.org/x/oauth2 for Keycloak token acquisition
# This example uses password grant against a local Keycloak (kc.sh start-dev).
---
auth:
  type: oauth2
  config:
    name: oauth2
    base_url: http://localhost:8080
    client_id: admin-cli
    # client_secret: ""
    # For Keycloak dev (kc.sh start-dev), use admin credentials for password grant via golang.org/x/oauth2
    username: admin
    password: root
    token_url: http://localhost:8080/realms/master/protocol/openid-connect/token
    auth_url: http://localhost:8080/realms/master/protocol/openid-connect/auth
    # header: Authorization
    # optional; defaults to Authorization

migrate_dir: ./migration

env:
  - name: kc_base
    value: http://localhost:8080
  - name: username
    value: alice
  - name: password
    value: alice123
  - name: realm
    valueFromEnv: SAMPLE_REALM
