name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    name: Go Test
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Show Go version
        run: go version

      - name: Download dependencies
        run: go mod download

      - name: Vet
        run: go vet ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Staticcheck
        run: $(go env GOPATH)/bin/staticcheck ./...

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec (static analysis)
        run: |
          set -e
          $(go env GOPATH)/bin/gosec -no-fail -fmt=json -out=gosec-report.json ./...

      - name: Upload gosec report artifact
        uses: actions/upload-artifact@v4
        with:
          name: gosec-report
          path: gosec-report.json

      - name: Build (all packages)
        run: go build ./...

      - name: Run safe examples (self-contained, no external services)
        run: |
          set -e
          echo "Running examples/auth_embedded"
          go run ./examples/auth_embedded
          echo "Running examples/auth_embedded_multi_registry"
          go run ./examples/auth_embedded_multi_registry
          echo "Running examples/auth_registry"
          go run ./examples/auth_registry
          echo "Running examples/embedded_sqlite"
          go run ./examples/embedded_sqlite
          echo "Running examples/embedded_custom_table"
          go run ./examples/embedded_custom_table
        env:
          CI: true

      - name: Build examples that require external services (do not run)
        run: |
          set -e
          go build ./examples/embedded
          go build ./examples/embedded_postgresql

      - name: Run tests with coverage (exclude examples)
        env:
          CGO_ENABLED: 1
        run: go test -p 1 -race -covermode=atomic -coverprofile=coverage.out $(go list ./... | grep -v '/examples/')

      - name: Show coverage summary
        run: go tool cover -func=coverage.out | tail -n 1

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out

  publish-coverage:
    name: Publish Coverage (Shields)
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: .

      - name: Extract coverage percentage
        shell: bash
        run: |
          set -euo pipefail
          LINE=$(go tool cover -func=coverage.out | tail -n 1)
          PCT=$(echo "$LINE" | awk '{print $3}')
          PCT_NUM=${PCT%%%}
          if [ "${PCT_NUM%.*}" -ge 80 ]; then COLOR=brightgreen
          elif [ "${PCT_NUM%.*}" -ge 60 ]; then COLOR=yellow
          else COLOR=red
          fi
          echo "COVERAGE=$PCT_NUM" >> "$GITHUB_ENV"
          echo "BADGE_COLOR=$COLOR" >> "$GITHUB_ENV"

      - name: Prepare Shields endpoint JSON
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p shields
          cat > shields/coverage.json <<EOF
          {
            "schemaVersion": 1,
            "label": "coverage",
            "message": "${COVERAGE}%",
            "color": "${BADGE_COLOR}"
          }
          EOF

      - name: Publish coverage endpoint to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: shields
          destination_dir: shields
          keep_files: true
          commit_message: "chore(ci): publish coverage endpoint (Shields)"
