name: Nightly Fuzz

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  fuzz:
    name: Go Fuzz (time-limited)
    runs-on: ubuntu-latest
    timeout-minutes: 70
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Show Go version
        run: go version

      - name: Download dependencies
        run: go mod download

      - name: Run fuzzing on internal packages
        shell: bash
        run: |
          set -euo pipefail
          packages=$(go list ./internal/env ./internal/store ./internal/migration ./internal/task ./internal/httpc ./internal/util)
          for pkg in $packages; do
            echo "Running fuzz on $pkg"
            go test $pkg -run=^$ -fuzz=Fuzz -fuzztime=10m
          done

      - name: Build (sanity)
        run: go build ./...

      - name: Upload fuzz artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fuzz-artifacts
          path: |
            internal/**/testdata/fuzz/corpus
            internal/**/testdata/fuzz/crashers
          if-no-files-found: ignore
